server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:      
      discovery:
        locator:
          enabled: true
      routes:
        - id: msv-users
          uri: lb://msv-users
          predicates:
            - Path=/api/users/**
          filters:
            - AuthFilter
        - id: msv-order
          uri: lb://msv-order
          predicates:
            - Path=/api/orders/**
        - id: msv-products
          uri: lb://msv-products
          predicates:
            - Path=/api/products/**,/api/categories/**,/api/discounts/**,/api/featured/**
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
